language: cpp

cache:
  - ccache: true

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang
  - msvc

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - cd build
  - make
  - make test