language: cpp

cache:
  - ccache: true

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - cmake --build .
  - ctest --output-on-failure || exit 1